### ISSUE TITLE
Flat category and multiple stores cause the NoSuchEntityException

### ISSUE THREAD

**Issue by chiufuchang** [staempfli/magento2-module-seo#11]
Hi,
We set different stores in Magento 2. When we choose flat category option, the function getAlternatives:
staempfli/magento2-module-seo/Block/HrefLang.php Line 39-43
```php
public function getAlternatives()
    {
        $data = [];
        foreach ($this->getStores() as $store) {
            if ((!$this->isCurrentStore($store)) && $url = $this->getStoreUrl($store)) {
                $data[$this->getLocaleCode($store)] = $url;
            }
        }
        return $data;
    }
```
will cause 
magento/module-catalog/Model/CategoryRepository.php 141 
to throw exception:
```php
public function get($categoryId, $storeId = null)
    {
        $cacheKey = null !== $storeId ? $storeId : 'all';
        if (!isset($this->instances[$categoryId][$cacheKey])) {
            /** @var Category $category */
            $category = $this->categoryFactory->create();
            if (null !== $storeId) {
                $category->setStoreId($storeId);
            }
            $category->load($categoryId);
            if (!$category->getId()) {
                throw NoSuchEntityException::singleField('id', $categoryId);
            }
            $this->instances[$categoryId][$cacheKey] = $category;
        }
        return $this->instances[$categoryId][$cacheKey];
    }
```
It will load category from flat category table for a specific store(For example:catalog_category_flat_store_5) but not the category table for all stores. It will return empty result and cause CategoryRepository.php to throw exception.

**Comment by mhauri** [comment]
Hi @chiufuchang thank you for the detailed description, can you tell me which Magento Version you use. I tested it on 2.2.4 and couldn't reproduce your issue.

**Comment by chiufuchang** [comment]
Magneto 2.2.3, thanks.
 I upgraded to 2.2.5, but it still has the same problem.
Following is the exception:

1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with id = 123

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with id = 123
#0 /opt/magento/public_html/vendor/magento/module-catalog/Model/CategoryRepository.php(141): Magento\Framework\Exception\NoSuchEntityException::singleField('id', '123')
#1 /opt/magento/public_html/vendor/staempfli/magento2-module-seo/Service/HrefLang/CategoryUrlRetriever.php(38): Magento\Catalog\Model\CategoryRepository->get('123', '5')
#2 /opt/magento/public_html/vendor/staempfli/magento2-module-seo/Service/HrefLang/AlternativeUrlService.php(50): Staempfli\Seo\Service\HrefLang\CategoryUrlRetriever->getUrl('123', Object(Magento\Store\Model\Store\Interceptor))
#3 /opt/magento/public_html/vendor/staempfli/magento2-module-seo/Block/HrefLang.php(53): Staempfli\Seo\Service\HrefLang\AlternativeUrlService->getAlternativeUrl(Object(Magento\Store\Model\Store\Interceptor))
#4 /opt/magento/public_html/vendor/staempfli/magento2-module-seo/Block/HrefLang.php(40): Staempfli\Seo\Block\HrefLang->getStoreUrl(Object(Magento\Store\Model\Store\Interceptor))
#5 /opt/magento/public_html/vendor/staempfli/magento2-module-seo/view/frontend/templates/hreflang.phtml(4): Staempfli\Seo\Block\HrefLang->getAlternatives()
#6 /opt/magento/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/opt/magento/pu...')
#7 /opt/magento/public_html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Staempfli\Seo\Block\HrefLang), '/opt/magento/pu...', Array)
#8 /opt/magento/public_html/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/opt/magento/pu...')
#9 /opt/magento/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#10 /opt/magento/public_html/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#11 /opt/magento/public_html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('seo.href.lang')
#12 /opt/magento/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('seo.href.lang')
#13 /opt/magento/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('seo.href.lang')
#14 /opt/magento/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('seo.href.lang', true)
#15 /opt/magento/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(511): Magento\Framework\View\Layout\Interceptor->renderElement('seo.href.lang', true)
#16 /opt/magento/public_html/vendor/magento/module-theme/view/frontend/templates/html/container.phtml(10): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#17 /opt/magento/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/opt/magento/pu...')
#18 /opt/magento/public_html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template), '/opt/magento/pu...', Array)
#19 /opt/magento/public_html/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/opt/magento/pu...')
#20 /opt/magento/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#21 /opt/magento/public_html/vendor/magento/framework/View/Result/Page.php(250): Magento\Framework\View\Element\AbstractBlock->toHtml()
#22 /opt/magento/public_html/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#23 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#24 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#25 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#26 /opt/magento/public_html/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(26): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#27 /opt/magento/public_html/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#28 /opt/magento/public_html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#29 /opt/magento/public_html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#30 {main}

**Comment by matutetandil** [comment]
It does reproduce in 2.3 as well. I removed the store parameter from vendor/staempfli/magento2-module-seo/Service/HrefLang/CategoryUrlRetriever.php line 38 just to let me continue developing (we are not live yet).
