### ISSUE TITLE
Each language version must list itself as well as all other language versions

### ISSUE THREAD

**Issue by nicobatty** [staempfli/magento2-module-seo#12]
Hi,

Your module seems to exclude the current store for the alternate links even though it is specified in google that it must list itself.

Our SEO specialist is also confirming this.

Google documentation on alternate links: "Each language version must list itself as well as all other language versions"
https://support.google.com/webmasters/answer/189077?hl=en

Code involved:
https://github.com/staempfli/magento2-module-seo/blob/d5e6370b83232fa0a2884ef4d989197ff59a546a/Block/HrefLang.php#L40

**Comment by mhauri** [comment]
Thank you @nicobatty I will take care of it.

**Comment by nicobatty** [comment]
Though, if only change this, it will add an alternate link to the websites with a single store view.

There might need to be a check if the store count is greater than 1.
