### ISSUE TITLE
Merge develop branch with master

### ISSUE THREAD

**Issue by Tjitse-E** [staempfli/magento2-module-seo#14]
Hi,

Thank you for the work on this module!

When will you merge the latest changes on the develop branch to the master branch? For example, [this commit](https://github.com/staempfli/magento2-module-seo/commit/bc1ee5407afd7f8c75da4d67b74bb79893c3a62c) seems ready to release.

**Comment by mhauri** [comment]
Thank you for your patience, merged it into master
