### ISSUE TITLE
Missing argument 3 in afterGetModulesByFrontName()

### ISSUE THREAD

**Issue by shinesoftware** [staempfli/magento2-module-seo#15]
Hello guys,

I have installed this module in Magento 2.1.15 and I get this error: 

> Exception #0 (Exception): Warning: Missing argument 3 for Staempfli\Seo\Plugin\RouteConfigPlugin::afterGetModulesByFrontName(), called in /lib/internal/Magento/Framework/Interception/Interceptor.php on line 152 and defined in /vendor/staempfli/magento2-module-seo/Plugin/RouteConfigPlugin.php on line 19

Any idea?

**Comment by mhauri** [comment]
Hi @shinesoftware please use Version 1.6.1 as version 1.6.2 and upwards is no longer compatible with Magento 2.1.
