### ISSUE TITLE
Compatibility with Magento 2.3.x

### ISSUE THREAD

**Issue by matutetandil** [staempfli/magento2-module-seo#16]
Hi! I'd like to know if the extension is compatible with Magento 2.3.x.

Thanks!

**Comment by simonmaass** [comment]
same here!

**Comment by mhauri** [comment]
Hi @matutetandil and @simonmaass will work on it asap.

**Comment by mhauri** [comment]
Please checkout: https://github.com/staempfli/magento2-module-seo/releases/tag/1.7.0

**Comment by simonmaass** [comment]
@mhauri thank you!!
