### ISSUE TITLE
does not share image on twitter card

### ISSUE THREAD

**Issue by to8gal** [staempfli/magento2-module-seo#19]
I am not able to share product image to Twitter cause as pointed in different post regarding this problem (but not specifically with Magento2 and your extension) Twitter has changed `twitter:image` to `twitter:image:src`

where do I change this?

**Comment by mhauri** [comment]
Hi @to8gal where did you found this change, as it isn't mentioned in the developer docs on twitter.
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image.html
