### ISSUE TITLE
Error: Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by piorus** [staempfli/magento2-module-seo#26]
`\Staempfli\Seo\Model\Property::getFilteredInput` filters data incorrectly when using non-english characters in product description, which causes
`\Staempfli\Seo\Model\Property::setDescription` to set og:description and twitter:description to the value containing non-utf8 character. This non-utf8 character crashes Magento2 when trying to execute 
`\Magento\Framework\App\PageCache\Kernel::process:151`

Example product description:
```
<p>Kurtka robocza HAMMER z odpinanymi rękawami co daje nam bezrękawnik.</p>
<p><strong>Charakterystyka:</strong></p>
<ul>
<li>Gramatura: 270 g/m2</li>
<li>Kurtka wykonana z T/S 35% bawełna / 65% poliester</li>
<li>Dodatki wzmacniające wykonane z materiału odpornego na ścieranie/rozerwanie - oxford</li>
<li>Posiada odpinane rękawy</li>
<li>Kolor: szary</li>
</ul>
<p><strong>Zastosowanie:</strong></p>
<ul>
<li>Prace budowlane</li>
<li>Terenowe</li>
<li>W warsztatach samochodowych</li>
</ul>
```

html meta tag generated by Staempfli\Seo module:
`<meta property="og:description" content="Kurtka robocza HAMMER z odpinanymi rękawami co daje nam bezrękawnik.Charakterystyka:Gramatura: 270 g/m2Kurtka wykonana z T/S 35% bawełna / 65% poliesterDodatki wzmacniające wykonane z materia� ..." />`

### Preconditions (*)
"staempfli/magento2-module-seo": "^1.7"
Magento 2.x

### Steps to reproduce (*)
1. Set product description  that have non-english character at the end of the substr
2. Save product
3. Product Detail Page won't load and throw `Exception #0 (InvalidArgumentException): Unable to serialize value. Error: Malformed UTF-8 characters, possibly incorrectly encoded`

### Expected result (*)
PDP loads correctly.

### Actual result (*)
PDP throws exception.

**Comment by DegrizNet** [comment]
I had the same problem and I fixed it with changing
`            $description = substr($description, 0, (self::MAX_DESCRIPTION_LENGTH - 4)) . ' ...';`
to
```
			$stringdesc = mb_substr($description, 0, (self::MAX_DESCRIPTION_LENGTH - 4), 'UTF-8');
			$description = utf8_decode($stringdesc); 
```
