### ISSUE TITLE
href alternative lang page links at website scope?

### ISSUE THREAD

**Issue by imino123** [staempfli/magento2-module-seo#31]
Is there a way to get this module to display href alternate lang tags for pages at website scope levels?

I have Magento 2 setup like this:

website 1: example.com/gb    (UK website)
website 2: example.com/us    (US website)
website 2: example.com/fr    (France website)
website 3: example.com/de    (Germany website)

The categories, menu and products are all identical. They have just been translated to accommodate more languages.

**Comment by audef1** [comment]
Yes, feel free to fork and implement it yourself. We've abandoned every magento2 module and we'll no longer develop for magento 2.
